import Link from "next/link";
import { SiteLogo } from "@/app/components/site-logo";

const h2 = "text-xl font-medium font-serif text-gray-950 mt-10 mb-3";
const p = "text-[0.9375rem] text-gray-700 leading-relaxed mb-4";
const ul = "list-disc pl-5 space-y-1.5 text-[0.9375rem] text-gray-700 leading-relaxed mb-4";

export const metadata = {
    title: "Privacy Policy — Rose",
};

export default function PrivacyPage() {
    return (
        <div className="min-h-dvh bg-gray-50/80">
            <div className="mx-auto max-w-3xl px-6 pt-16 pb-24">
                <div className="mb-10">
                    <SiteLogo size="md" asLink />
                </div>

                <h1 className="text-3xl font-medium font-serif text-gray-950 mb-2">
                    Privacy Policy
                </h1>
                <p className="text-sm text-gray-500 mb-10">
                    Last updated: 25 July 2026
                </p>

                <p className={p}>
                    Rose is a research and educational tool developed by Peter
                    Dombkins, Adjunct Associate Professor in Legal
                    Transformation at UNSW, to teach how AI-assisted legal
                    tools are built. This policy explains what personal
                    information Rose collects, how it is used, and your
                    rights, consistent with the Privacy Act 1988 (Cth) and the
                    Australian Privacy Principles (APPs).
                </p>

                <h2 className={h2}>1. Information we collect</h2>
                <p className={p}>We collect:</p>
                <ul className={ul}>
                    <li>
                        <strong>Account information</strong> — name, email
                        address, organisation/institution, and password
                        (stored in hashed form by our authentication
                        provider, Supabase).
                    </li>
                    <li>
                        <strong>Content you provide</strong> — documents you
                        upload, prompts and messages you send, and any
                        projects, notes, clauses, or playbooks you create
                        within Rose.
                    </li>
                    <li>
                        <strong>Usage and cost data</strong> — which features
                        you use, and the token/cost of each AI request, so
                        that usage can be tracked and, where enabled, kept
                        within a budget.
                    </li>
                    <li>
                        <strong>Technical data</strong> — basic log data (such
                        as timestamps and error records) generated by normal
                        operation of the Service.
                    </li>
                </ul>
                <p className={p}>
                    We do not use third-party advertising or analytics
                    trackers (such as Google Analytics or similar tools) on
                    Rose.
                </p>

                <h2 className={h2}>2. How we use your information</h2>
                <p className={p}>We use the information above to:</p>
                <ul className={ul}>
                    <li>provide, operate, and maintain the Service;</li>
                    <li>
                        process your requests through AI model providers and
                        return a response to you;
                    </li>
                    <li>
                        send account-related email, such as sign-up
                        confirmations, invitations, and notifications you have
                        opted into;
                    </li>
                    <li>
                        monitor and, where applicable, enforce usage budgets
                        and course/group access; and
                    </li>
                    <li>
                        maintain the security, integrity, and academic
                        integrity of the Service (for example, audit logs of
                        actions taken within a shared teaching project).
                    </li>
                </ul>

                <h2 className={h2}>3. Overseas disclosure</h2>
                <p className={p}>
                    Because Rose relies on overseas-hosted infrastructure and
                    AI providers, some personal information is disclosed
                    outside Australia. Under Australian Privacy Principle 8,
                    we are required to take reasonable steps to ensure
                    overseas recipients handle your information consistently
                    with the APPs. The relevant recipients are:
                </p>
                <ul className={ul}>
                    <li>
                        <strong>Supabase</strong> (authentication and
                        database) — hosted in Singapore.
                    </li>
                    <li>
                        <strong>Cloudflare</strong> (file/document storage and
                        website hosting) — a global network with facilities
                        outside Australia.
                    </li>
                    <li>
                        <strong>Anthropic (Claude), Google (Gemini), and
                        Moonshot AI</strong> — AI model providers based in the
                        United States/China respectively, used to generate
                        responses to your prompts and documents. Content you
                        submit to Rose (prompts, uploaded documents) may be
                        sent to whichever provider and model you have
                        selected.
                    </li>
                    <li>
                        <strong>Resend</strong> (transactional email) — used
                        to deliver account, invitation, and notification
                        emails.
                    </li>
                    <li>
                        <strong>Jade.io (BarNet)</strong> — where an
                        administrator has enabled Jade access with BarNet&rsquo;s
                        written permission, limited case/legislation queries
                        and citations may be sent to Jade.io to verify legal
                        citations. Where Jade access is not enabled, no
                        content is sent to Jade.io or AustLII by Rose; instead
                        you receive a search link to open in your own browser.
                    </li>
                </ul>
                <p className={p}>
                    We choose providers with their own privacy and security
                    commitments, but we cannot guarantee the practices of
                    every overseas recipient will match Australian law in
                    every respect. If you are not comfortable with your
                    content being processed by any of the above providers, do
                    not submit that content to Rose.
                </p>

                <h2 className={h2}>4. Data security</h2>
                <p className={p}>
                    We use industry-standard measures to protect your
                    information, including encrypted connections,
                    role-based access controls, and row-level security on our
                    database. No online system can be guaranteed completely
                    secure, and you should avoid uploading highly sensitive
                    personal information (such as health records or
                    government identifiers) unless it is genuinely necessary
                    for your research or coursework.
                </p>

                <h2 className={h2}>5. Data retention</h2>
                <p className={p}>
                    We retain account and content data for as long as your
                    account is active, or as needed for the research/teaching
                    purpose it was collected for. You can request deletion of
                    your account and associated content at any time (see
                    Contact below); some data may be retained briefly
                    afterwards where required for audit, security, or legal
                    reasons.
                </p>

                <h2 className={h2}>6. Your rights</h2>
                <p className={p}>
                    You may request access to, or correction of, the personal
                    information we hold about you by contacting us at the
                    email address below. If you believe we have mishandled
                    your personal information and are not satisfied with our
                    response, you may lodge a complaint with the Office of the
                    Australian Information Commissioner (OAIC) at{" "}
                    <a
                        href="https://www.oaic.gov.au"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline"
                    >
                        oaic.gov.au
                    </a>
                    .
                </p>

                <h2 className={h2}>7. Children</h2>
                <p className={p}>
                    Rose is intended for use by university students,
                    researchers, and educators, and is not directed at
                    children. We do not knowingly collect personal
                    information from children.
                </p>

                <h2 className={h2}>8. Changes to this policy</h2>
                <p className={p}>
                    We may update this Privacy Policy from time to time, for
                    example if we change which third-party providers we use.
                    The &ldquo;Last updated&rdquo; date above reflects the
                    most recent revision. Material changes will be reflected
                    on this page.
                </p>

                <h2 className={h2}>9. Contact</h2>
                <p className={p}>
                    Questions about this Privacy Policy, or requests to
                    access, correct, or delete your information, can be sent
                    to{" "}
                    <a
                        href="mailto:pdombkins@gmail.com"
                        className="text-blue-600 hover:underline"
                    >
                        pdombkins@gmail.com
                    </a>
                    . See also our{" "}
                    <Link href="/terms" className="text-blue-600 hover:underline">
                        Terms of Use
                    </Link>
                    .
                </p>
            </div>
        </div>
    );
}
